import { DefaultLayout } from "#components/layouts/default";
import { NextPageWithLayout } from "#utils/types";
import type { NextPage } from "next";
import Head from "next/head";
import { ReactElement } from "react";

type Props = {};

const Home: NextPageWithLayout<Props> = (props) => {
  return (
    <div>
      <Head>
        <title>Hooshu&apos;s Custom Next App</title>
        <meta name="description" content="Generated by Hooshu" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello, World!</h1>
    </div>
  );
};

Home.getLayout = function (page: ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
